age = input("How old r u? ")
height = input("How tall r u? ")
weight = input("How much do you weight? ")
print("How old are you?",input())
print(f"So, you're {age} old, {height} tall and {weight} heavy1.")
